# Tensor in PyTorch

## Variable and Tensor

**Variable**是torch.autograd中的数据类型，主要封装Tensor，进行自动求导。

* data: 被包装的Tensor

* grad: data的梯度

* grad_fn: 创建Tensor的Function, 是自动求导的关键

* requires_grad: 是否需要梯度

* is_leaf: 是否是叶子结点(张量)

## Tensor

Tensor是PyTorch数据结构。

* dtype: 张量的数据类型

* shape: 张量的形状

* device: 张量所在设备, GPU/CPU， 是加速的关键。

## 创建Tensor

### 直接创建

In [2]:
import torch
import numpy as np

In [5]:
arr = np.ones((3, 3))

In [6]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
t = torch.tensor(arr)

In [8]:
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### 通过Numpy创建

array与Tensor共享内存。

In [9]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
t1 = torch.from_numpy(arr1)

In [12]:
t1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
arr1[0, 0] = 0

In [14]:
t1

tensor([[0, 2, 3],
        [4, 5, 6]])

## 依据数值创建张量

 #### torch.zeros()
 
 * size: 张量的形状
 
 * out: 输出的张量
 
 * layout: 内存中布局形式
 
 * device: 所在设备
 
 * requires_grad: 是否需要梯度

 
 #### torch.zeros_like()

In [15]:
zeros = torch.zeros((3,3))

In [16]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])